### ISSUE TITLE
about tensorflow 2.0 for raspberry

### ISSUE THREAD

**Issue by dhdljd** [jingw222/raspicam_vision_lite#2]
Hi
    your project is very good. it is so suitable for learning and testing my project , thank you. But i have some problem.should i install a total tensorflow2.0 on my raspberry or just lite library libtensorflow-lite.a .i try to install tensorflow2.0 on my rasp from source used offical ci_build with cross-build (if install from whl offically the edition is not the 2.0,just 1.13),i have faild many times .so can i use just tensorflow 1.13 in you project or do you have a tensorflow2.0 whl file for ransp :) thankyou very much

**Comment by dhdljd** [comment]
i have known this. i can use tflite_runtime.interpreter instead of tf.lite.interpreter. but still i can not install tensorflow full package in my rasp

**Comment by jingw222** [comment]
Hi @dhdljd,

Sorry for the late response and many thanks to your appreciation. 

Regarding the TensorFlow 2.0 installation on my Raspbian 9, I used precompiled working wheels from [PINTO0309](https://github.com/PINTO0309/Tensorflow-bin), specifically, `tensorflow-2.0.0b1-cp35-cp35m-linux_armv7l.whl`. There are also packages for Python3.7 on Raspbian Buster, which is yet to be tested in this project though. Let me know if you'd have any other problems installing related libraries.

**Comment by dhdljd** [comment]
Thank you very much for your response. This is a big help for resolving my problem.



京能集团信息中心(英贝思科技)
----------------------------------------
方案中心
Beijing InBasis Technology Co.,Ltd. 北京英贝思科技有限公司
Tel: 18600234786   Fax: 010-85402800
E-mail：yukai@powerbeijing.com   http://www.inbasis.com
 
From: James Wong
Date: 2019-10-05 13:32
To: jingw222/raspicam_vision_lite
CC: dhdljd; Mention
Subject: Re: [jingw222/raspicam_vision_lite] about tensorflow 2.0 for raspberry (#2)
Hi @dhdljd,
Sorry for the late response and many thanks to your appreciation.
Regarding the TensorFlow 2.0 installation on my Raspbian 9, I used precompiled working wheels from PINTO0309, specifically, tensorflow-2.0.0b1-cp35-cp35m-linux_armv7l.whl. There are also packages for Python3.7 on Raspbian Buster, which is yet to be tested in this project though. Let me know if you'd have any other problems installing related libraries.
